version: "3"

services:

  postgres:
    container_name: postgres-bot
    image: postgres:12-alpine
    restart: always
    env_file:
      - .env
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - /usr/src/app/data:/var/lib/postgresql/data/pgdata

  redis:
    container_name: redis-bot
    image: redis:5-alpine
    restart: always
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - /usr/src/app/data:/bitnami/redis/data

  organizer:
    container_name: organizer-bot
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
  redis-data:
